from typing import BinaryIO, Protocol


class Storage(Protocol):
    def save(self, key: str, stream: BinaryIO) -> str: ...
    def url(self, key: str) -> str: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
